export const CATEGORIES_FETCH_SUCCESS = 'categories_fetch_success'
export const CATEGORY_ORGS_FETCH_SUCCESS = 'category_orgs_fetch_success'
export const ORGANIZATION_FETCH_SUCCESS = 'organization_fetch_success'
export const ORGANIZATION_CATS_FETCH_SUCCESS = 'organization_cats_success'
export const COORDINATES_FETCH_SUCCESS = 'coordinates_fetch_success'
export const LOCATION_FETCH_SUCCESS = 'location_fetch_success'
